---
- name: Install Nginx
  dnf:
    name: nginx
    state: present
  become: true

- name: Remove default Fedora Nginx configuration block
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  become: true

- name: Create custom Proxy Configuration
  copy:
    dest: /etc/nginx/conf.d/proxy.conf
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://10.0.2.114:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      }
  become: true
  notify: restart nginx

- name: Start and Enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Allow HTTP in Firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: Allow Nginx network connections (SELinux)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: true