---
- name: Install Nginx
  dnf:
    name: nginx
    state: present
  become: true

- name: Configure Nginx as a Reverse Proxy
  copy:
    dest: /etc/nginx/conf.d/proxy.conf
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://10.0.2.114:8000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
  become: true
  notify: restart nginx

- name: Start and Enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Allow HTTP (Port 80) in Firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: Allow Nginx to connect to network (SELinux)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: true  